//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2
{
    using System;
    using System.Collections.Generic;
    
    public partial class empleados
    {
        public int id { get; set; }
        public string nombreCompleto { get; set; }
        public string fechaNacimiento { get; set; }
        public string tipo { get; set; }
        public string domicilio { get; set; }
        public string usuario { get; set; }
        public string passusuario { get; set; }
    }
}
